/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentConfigPanel: typeof import('./src/components/agent/AgentConfigPanel.vue')['default']
    AgentInput: typeof import('./src/components/agent/AgentInput.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    Markdown: typeof import('./src/components/common/Markdown.vue')['default']
    PlanTree: typeof import('./src/components/agent/PlanTree.vue')['default']
    ReflectionBanner: typeof import('./src/components/agent/ReflectionBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionSelector: typeof import('./src/components/agent/SessionSelector.vue')['default']
    SkeletonList: typeof import('./src/components/common/SkeletonList.vue')['default']
    ThinkingStream: typeof import('./src/components/agent/ThinkingStream.vue')['default']
    ToolCallCard: typeof import('./src/components/agent/ToolCallCard.vue')['default']
  }
}
