apiVersion: v1
kind: Service
metadata:
  name: docmind-backend
  namespace: docmind
spec:
  selector:
    app: docmind-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
