apiVersion: v1
kind: Service
metadata:
  name: docmind-frontend
  namespace: docmind
spec:
  selector:
    app: docmind-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
